apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: nginx-ns
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
