apiVersion: v1
kind: Pod
metadata:
  name: busybox-load
  namespace: apache   # or notes-app, depending on which namespace your app runs in
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "Starting load generation..."
        while true; do
          wget -q -O- http://apache-service.apache.svc.cluster.local > /dev/null
        done
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
  restartPolicy: Never
